SET ECHO OFF
SET PAGESIZE 17
SET FEEDBACK OFF
SET LINESIZE 150

TTITLE EMPLOYEE-REPORT;
BTITLE Confidential;

COLUMN DEPNO HEADING DEPARTMENT TEMP;
COLUMN ENAME FORMAT A8 HEADING NAME TEMP;
COLUMN SAL FORMAT $9999.99;

SELECT * FROM EMP;
