SET ECHO OFF
SET PAGESIZE 24
SET FEEDBACK OFF
SER LINESIZE 90

TTITLE EMPLOYEE-REPORT;
BTITLE Confidential;

COLUMN DEPNO HEADING DEPATMENT TEMP;
COLUMN ENAME FORMAT A8 HEADING NAME TEMP;
COLUMN SAL FORMAT $9999.99;

SELECT *
FROM EMP;